name: Deploy To Google Play

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  distribute:
  name: Distribute bundle to Google Play
  needs: test
  runs-on: ubuntu-latest

  steps:
    # 1. Depoyu klonla
    - uses: actions/checkout@v4

    # 2. JDK 17 Kurulumu
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'

    # 3. Sürüm numarasını arttır
    - name: Version Bump
      uses: chkfung/android-version-actions@v1.2.3
      with:
        gradlePath: app/build.gradle.kts # Gradle dosyasının doğru yolu
        versionCode: ${{ github.run_number }}

    # 4. Release Bundle oluştur
    - name: Assemble Release Bundle
      run: ./gradlew bundleRelease

    # 5. Release AAB imzala
    - name: Sign Release
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        alias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

    # 6. Google Play Yetkilendirmesi
    - name: Setup Authorization with Google Play Store
      run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

    # 7. Google Play'e gönder
    - name: Deploy bundle to Google Play
      uses: r0adkll/upload-google-play@v1.1.3
      with:
        serviceAccountJson: service_account.json
        packageName: nl.jovmit.androiddevs # Paket adını kontrol edin
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: 'internal' # Alternatif: 'beta', 'production'
        status: 'completed'
        whatsNewDirectory: whatsNew/
