name: Deploy To Google Play

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  distribute:
    name: Distribute bundle to Google Play
    runs-on: ubuntu-latest

    steps:
      # 1. Kodu depodan al
      - uses: actions/checkout@v4

      # 2. Node.js ortamını kur ve bağımlılıkları yükle
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      # 3. JDK 17 ortamını kur
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      # 4. AAB dosyasını oluştur
      - name: Assemble Release Bundle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean bundleRelease --stacktrace --debug

      # 5. Release AAB'yi imzala
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      # 6. Google Play Yetkilendirmesini Ayarla
      - name: Setup Authorization with Google Play Store
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      # 7. Google Play'e yükle
      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service_account.json
          packageName: nl.jovmit.androiddevs
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: 'internal'
          status: 'completed'
          whatsNewDirectory: whatsNew/
