name: Android CI and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy Android App
    runs-on: ubuntu-latest

    steps:
      # 1. Kod deposunu klonla
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java ortamını kur
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: gradle

      # 3. Android SDK’yı kur
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools-version: 31.0.0
          cmake-version: 3.18.1

      # 4. Gradle build
      - name: Build with Gradle
        id: build
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean bundleRelease
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

      # 5. Keystore Dosyasını Decode Et ve AAB Dosyasını İmzala
      - name: Decode keystore file
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/release-key.keystore
      - name: Sign Android Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      # 6. AAB dosyasını kaydet
      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab

      # 7. Google Play’e yükle
      - name: Deploy to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.devfast
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: draft
