name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy Android App
    runs-on: ubuntu-latest

    steps:
      # 1. Kod deposunu klonla
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js ortamını kur
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Bağımlılıkları yükle
      - name: Install dependencies
        run: npm install

      # 4. Java ortamını kur
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: gradle

      # 5. Android SDK’yı kur
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools-version: 31.0.0
          cmake-version: 3.18.1

      # 6. Gradle wrapper doğrulaması
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # 7. Android uygulamasını build et
      - name: Build Android App
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean assembleRelease
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}  # Java'nın doğru yolu ayarlandı
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

      # 8. APK dosyasını kaydet
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
