name: Deploy to Play Store

on:
  push:
    branches:
      - main # Ana branch'a her push'ta çalışır

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build the app
        run: ./gradlew bundleRelease # aab dosyasını üretir

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: "com.devfast" # Uygulama Package ID'si
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal # Track türü: 'internal', 'beta', 'production' seçebilirsin
