name: Deploy to Google Play

on:
  push:
    branches:
      - main  # Deploy işlemini tetikleyecek branch'ı buraya yaz.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Download dependencies
      run: ./gradlew dependencies

    - name: Build AAB file
      run: ./gradlew bundleRelease

    - name: Upload to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: "com.devfast"  # Buraya uygulamanın paket adını yaz.
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: internal  # Hangi track'e yüklemek istediğini seç (internal, beta, production).
